import { Link } from "react-router-dom";
import { ArrowLeft, ArrowUpRight, Check, Copy, FileText, ImageSquare, Clock } from "@phosphor-icons/react";
import { ContentImage } from "../../components/ContentImage";
import { ReviewImages } from "../../components/ReviewImages";
import { Stars } from "./ReviewCenter";
import { OrderPayment } from "./OrderCard";
import { orderAmounts } from "./orderPresentation";
import { currency, orderStatus, refundStatus, invoiceStatus, type Order, type Refund, type Invoice, type Review } from "./accountData";
export function OrderDetail({order:o,refunds,invoices,reviews,onBack,onCopy,onAccept,onRefund,onInvoice,canRefund}:{order:Order;refunds:Refund[];invoices:Invoice[];reviews:Review[];onBack:()=>void;onCopy:()=>void;onAccept:()=>void;onRefund:()=>void;onInvoice:(invoice:Invoice)=>void;canRefund:boolean}) {
  const stage={pending:0,signing:2,serving:3,accepting:4,completed:5,closed:-1}[o.status];
  const relevantRefunds=refunds.filter(r=>r.orderId===o.id), invoice=invoices.find(i=>i.orderId===o.id), review=reviews.find(r=>r.orderId===o.id&&r.direction==="sent");
  const amounts=orderAmounts(o);
  return <div className="order-detail-page">
    <header className="order-detail-heading"><button className="v3-order-text-action" onClick={onBack}><ArrowLeft size={18}/>返回订单列表</button><h1>订单详情</h1><span>订单编号：{o.id}<button aria-label="复制订单编号" onClick={onCopy}><Copy size={16}/></button></span></header>
    <div className="order-detail-stepper" aria-label="订单流程">{["提交订单","付款安排","签署合同","服务履约","成果验收","订单完成"].map((name,i)=><div key={name} className={stage>=i?"is-reached":""} aria-current={stage===i?"step":undefined}><span>{stage>i?<Check size={16}/>:i+1}</span><strong>{name}</strong></div>)}</div>
    <div className="order-detail-grid"><div className="order-detail-content">
      <section className="detail-block"><header><h2>服务信息</h2><div><span className={`v3-status v3-status-${o.status}`}>{orderStatus[o.status]}</span>{o.refunded>0&&<span className="v3-order-refund-label">{o.refunded>=o.paid?"全额退款":"部分退款"}</span>}</div></header><div className="detail-service"><ContentImage src={o.image} alt={o.name} placeholder="" placeholderIcon={<ImageSquare size={38}/>}/><div><Link to={`/services/${o.serviceId}`}><h3>{o.name}<ArrowUpRight size={16}/></h3></Link><span className="v3-order-fulfillment">{o.paymentMode==="installments"?"分期支付":"一次支付"} · {o.phases>1?"阶段验收":"一次验收"}</span><dl className="detail-facts"><div><dt>服务分类</dt><dd>{o.category}</dd></div><div><dt>服务规格</dt><dd>{o.spec}</dd></div><div><dt>交付周期</dt><dd>{o.deliveryDays?`${o.deliveryDays}个自然日` : "双方确认"} · 共{o.phases}个阶段</dd></div><div><dt>服务机构</dt><dd>{o.provider}</dd></div></dl></div><div className="detail-unit"><strong className="amount-emphasis">{currency(o.total/o.quantity)}</strong><span>× {o.quantity}</span></div></div></section>
      <section className="detail-block"><header><h2>签约合同</h2><span>{o.contract?.signedAt&&`签署时间：${o.contract.signedAt}`}</span></header>{o.contract?<div className="detail-file"><FileText size={30}/><div><strong>{o.contract.name}</strong><small>{o.contract.status==="signed"?"合同已签署":"等待双方确认并签署合同"}</small></div>{o.contract.url&&/^https?:\/\//.test(o.contract.url)?<a className="button secondary" target="_blank" rel="noreferrer" href={o.contract.url}>查看合同</a>:<span>{o.contract.status==="signed"?"文件待同步":"待签署"}</span>}</div>:<p className="detail-muted">暂无合同记录，服务范围与费用以双方确认的方案为准。</p>}</section>
      <section className="detail-block"><header><h2>阶段交付与验收</h2><span>共 {o.phases} 个阶段</span></header>{o.acceptanceDeadline&&o.status==="accepting"&&<div className="detail-callout"><Clock size={18}/><span>请于 {new Date(o.acceptanceDeadline).toLocaleString("zh-CN")} 前核对交付成果{o.autoAccept?"，到期按约定自动验收":""}。</span></div>}{o.deliveries?.length?o.deliveries.map((d,i)=><article className="delivery-stage" key={i}><header><span className="stage-number">{String(i+1).padStart(2,"0")}</span><h3>{d.name}</h3><span className={`v3-status v3-status-${{waiting:"pending",working:"serving",submitted:"accepting",accepted:"completed"}[d.status]}`}>{{waiting:"待开始",working:"履约中",submitted:"待验收",accepted:"已验收"}[d.status]}</span></header><p><b>交付标准</b>{d.standard}</p>{d.fileName&&<div className="detail-file"><FileText size={24}/><div><strong>{d.fileName}</strong><small>提交时间：{d.submittedAt}</small></div>{d.fileUrl&&/^https?:\/\//.test(d.fileUrl)?<a href={d.fileUrl} target="_blank" rel="noreferrer">查看交付物</a>:<small>交付文件待同步</small>}</div>}</article>):<p className="detail-muted">阶段交付信息待服务商补充。</p>}{o.status==="accepting"&&<div className="detail-section-actions"><span>请先检查交付成果，再确认验收。</span><button className="button primary" onClick={onAccept}>确认验收</button></div>}</section>
      <section className="detail-block"><h2>付款记录</h2>{o.payments?.length?<table className="detail-payment-table"><thead><tr><th>付款阶段</th><th>支付金额</th><th>支付时间</th><th>状态</th></tr></thead><tbody>{o.payments.map((p,i)=><tr key={i}><td>{p.label}</td><td>{currency(p.amount)}</td><td>{p.paidAt}</td><td><span className="v3-status v3-status-completed">已支付</span></td></tr>)}</tbody></table>:<p className="detail-muted">{o.paid?`累计实付 ${currency(o.paid)}，支付流水待同步。`:"暂无付款记录。"}</p>}{amounts.remaining>0&&<p className="detail-callout">尚待支付 {currency(amounts.remaining)}，具体付款节点以合同约定为准。</p>}</section>
      {!!relevantRefunds.length&&<section className="detail-block"><h2>售后记录</h2>{relevantRefunds.map(r=><Link key={r.id} className="detail-related-refund" to="/account/aftersales"><div><strong>{r.id}</strong><p>{r.reason}</p></div><span>{currency(r.amount)}</span><span className={`v3-status v3-status-${r.status}`}>{refundStatus[r.status]}</span><ArrowUpRight size={16}/></Link>)}</section>}
      {review&&<section className="detail-block"><header><h2>服务评价</h2><span>评价时间：{review.createdAt}{review.hidden?" · 已隐藏":""}</span></header><div className="order-review"><span className="review-avatar" aria-hidden="true">{review.anonymous?"匿":"我"}</span><div className="order-review-body"><Stars score={review.score}/><p>{review.content||`已给出${review.score}星评价，未填写文字内容。`}</p><ReviewImages images={review.images}/>{review.followup&&<blockquote>追评：{review.followup.content}</blockquote>}{review.reply&&<blockquote>商家回复：{review.reply}</blockquote>}</div></div></section>}
      <section className="detail-block"><h2>订单动态</h2><ol className="detail-timeline">{o.progress.map((p,i)=><li key={i}><span><Check size={16}/></span><div><strong>{p.title}</strong><time>{p.date}</time><p>{p.detail}</p></div></li>)}</ol></section>
    </div><aside className="order-detail-summary"><section className="detail-block"><h2>费用明细</h2><OrderPayment order={o}/><div className="detail-invoice-total"><span>可开票金额</span><strong className="amount-emphasis">{currency(invoice?.amount??Math.max(0,o.paid-o.refunded))}</strong></div><p className="detail-muted">按实际支付减去已退款金额计算，具体开票状态以记录为准。</p><h3>订单信息</h3><dl className="detail-facts"><div><dt>创建时间</dt><dd>{o.createdAt}</dd></div><div><dt>付款方式</dt><dd>{o.paymentMode==="installments"?"分期付款":"一次付款"}</dd></div><div><dt>发票状态</dt><dd>{invoice?invoiceStatus[invoice.status]:"暂无开票记录"}</dd></div></dl><div className="detail-summary-actions">{invoice&&<button className="button primary" onClick={()=>onInvoice(invoice)}>{invoice.status==="available"?"申请开票":"查看发票"}</button>}{o.status==="completed"&&<Link className="button secondary" to="/account/reviews">评价服务</Link>}{canRefund&&<button className="v3-order-text-action" onClick={onRefund}>申请售后退款</button>}</div></section></aside></div>
  </div>;
}
