import { Copy, Info, ArrowRight } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { currency, refundStatus, type Refund, type Order } from "./accountData";
export const refundKind=(refund:Refund,order?:Order)=>refund.kind==="terminate"?"退款并解约":refund.kind==="partial"||(order&&refund.amount<order.paid)?"部分退款":"申请退款";
export function RefundCard({refund:r,order,onDetails,onEdit,onCancel,onProposal,onCopy}:{refund:Refund;order?:Order;onDetails:()=>void;onEdit:()=>void;onCancel:()=>void;onProposal:(accept:boolean)=>void;onCopy:()=>void}) {
  const negotiating=r.status==="processing"&&r.proposal?.status==="pending";
  return <article className="aftercare-card">
    <header><div className="aftercare-meta"><time>{r.createdAt}</time><span>售后编号：{r.id}<button aria-label={`复制售后编号 ${r.id}`} onClick={onCopy}><Copy size={14}/></button></span><b>{r.provider}</b></div><span className={`v3-status v3-status-${r.status}`}>{refundStatus[r.status]}</span></header>
    <div className="aftercare-body"><div className="aftercare-info"><h2>{r.name}</h2><span className="v3-order-fulfillment">{refundKind(r,order)}</span><dl><div><dt>关联订单</dt><dd><Link to={`/account/orders/services?order=${r.orderId}`}>{r.orderId}</Link></dd></div><div><dt>申请原因</dt><dd>{r.reason}</dd></div></dl></div>
      <div className="aftercare-money"><span>{negotiating?"协商退款金额":r.status==="refunded"?"已退款金额":"申请退款金额"}</span><strong className="amount-emphasis">{currency(negotiating?r.proposal!.amount:r.amount)}</strong>{negotiating&&<small>原申请 {currency(r.amount)}</small>}{order&&<small>订单实付款 {currency(order.paid)}</small>}</div>
      <div className="v3-order-actions aftercare-actions">{r.status==="rejected"&&<button className="button primary" onClick={onEdit}>修改重提</button>}<button className={`v3-order-text-action${r.status==="rejected"||negotiating?"":" is-leading"}`} onClick={onDetails}>售后详情</button><Link className="v3-order-text-action" to={`/account/orders/services?order=${r.orderId}`}>查看原订单</Link>{["processing","rejected"].includes(r.status)&&<button className="v3-order-text-action is-muted" onClick={onCancel}>取消申请</button>}</div>
    </div>
    {negotiating?<div className="aftercare-negotiation"><div className="aftercare-notice-title"><Info size={18}/><strong>服务商建议调整退款金额，请确认方案</strong><time>{r.proposal!.createdAt}</time></div><p className="aftercare-proposal">{r.proposal!.reason}</p><div className="aftercare-decision"><dl className="aftercare-amount-flow"><div><dt>原申请金额</dt><dd className="amount-emphasis">{currency(r.amount)}</dd></div><div className="aftercare-amount-arrow" aria-hidden="true"><ArrowRight size={18}/></div><div className="is-suggested"><dt>建议退款金额</dt><dd className="amount-emphasis">{currency(r.proposal!.amount)}</dd></div></dl><div className="aftercare-decision-actions"><small>确认后等待退款处理，到账后更新可开票金额。</small><button className="button danger" onClick={()=>onProposal(false)}>拒绝调整</button><button className="button primary" onClick={()=>onProposal(true)}>同意方案</button></div></div></div>:r.note&&<div className={`aftercare-feedback ${r.status==="rejected"?"is-rejected":""}`}><Info size={17}/><p><b>{r.status==="rejected"?"驳回原因：":"处理反馈："}</b>{r.note}</p></div>}
  </article>;
}
export function RefundDetail({refund:r,order}:{refund:Refund;order?:Order}) {
  return <div className="aftercare-detail"><div className="detail-status-banner"><div><span className={`v3-status v3-status-${r.status}`}>{refundStatus[r.status]}</span><h2>{r.name}</h2><p>售后编号：{r.id} · {r.createdAt}</p></div><div><small>{refundKind(r,order)}</small><strong className="amount-emphasis">{currency(r.amount)}</strong></div></div>
    <section className="detail-block"><h3>关联服务与合同</h3><dl className="detail-facts"><div><dt>原订单</dt><dd>{r.orderId}</dd></div><div><dt>服务机构</dt><dd>{r.provider}</dd></div><div><dt>服务专员</dt><dd>{order?.contact?.name||"以服务商确认为准"}</dd></div><div><dt>服务规格</dt><dd>{order?.spec||"—"}</dd></div></dl>{order?.contract&&<p className="detail-file">{order.contract.name}<span>{order.contract.status==="signed"?"已签署":"待签署"}</span>{order.contract.url&&/^https?:\/\//.test(order.contract.url)?<a href={order.contract.url} target="_blank" rel="noreferrer">查看合同</a>:<small>合同文件待同步</small>}</p>}</section>
    <section className="detail-block"><h3>退款诉求</h3><dl className="detail-facts"><div><dt>申请原因</dt><dd>{r.reason}</dd></div></dl><p>{r.description||r.reason}</p>{r.proposal&&<div className="detail-callout"><strong>金额协商 · {r.proposal.status==="pending"?"待确认":r.proposal.status==="accepted"?"已同意":"已拒绝"}</strong><p>建议退款 {currency(r.proposal.amount)} · {r.proposal.reason}</p></div>}</section>
    <section className="detail-block"><h3>处理进度</h3><ol className="detail-timeline">{(r.history?.length?r.history:[{title:"提交退款申请",date:r.createdAt,detail:r.reason},{title:refundStatus[r.status],date:"",detail:r.note}]).map((event,i)=><li key={i}><span>{i+1}</span><div><strong>{event.title}</strong><time>{event.date}</time><p>{event.detail}</p></div></li>)}</ol></section><Link className="button secondary" to={`/account/orders/services?order=${r.orderId}`}>查看原订单 <ArrowRight size={16}/></Link></div>;
}
