import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Star, ImageSquare, ChatCircleText, CheckCircle } from "@phosphor-icons/react";
import { ContentImage } from "../../components/ContentImage";
import { AdaptiveTabs } from "../../components/AdaptiveTabs";
import { EmptyState, Modal, ErrorNotice } from "../../components/ui";
import type { Order, Review, AccountAction } from "./accountData";
function Stars({score}:{score:number}) { return <span className="review-stars" aria-label={`${score}星评价`}>{[1,2,3,4,5].map(n=><Star key={n} size={20} weight={n<=score?"fill":"regular"}/>)}<strong>{["","有待改进","一般","满意","很满意","超赞"][score]}</strong></span>; }
export function ReviewCenter({orders,reviews,onAction,pending,error}:{orders:Order[];reviews:Review[];onAction:(action:AccountAction)=>Promise<boolean>;pending:boolean;error:unknown}) {
  const [tab,setTab]=useState("pending"),[editing,setEditing]=useState<{order:Order;review?:Review}|null>(null);
  const [score,setScore]=useState(5),[content,setContent]=useState(""),[anonymous,setAnonymous]=useState(false),[validation,setValidation]=useState("");
  const [page,setPage]=useState(1);
  useEffect(()=>setPage(1),[tab]);
  const eligible=orders.filter(o=>o.status==="completed"&&!reviews.some(r=>r.orderId===o.id&&r.direction==="sent"));
  const sent=reviews.filter(r=>r.direction==="sent"),received=reviews.filter(r=>r.direction==="received");
  const current=tab==="sent"?sent:received;
  const listLength=tab==="pending"?eligible.length:current.length;
  const pageSize=10;
  const pageCount=Math.max(1,Math.ceil(listLength/pageSize));
  const currentPage=Math.min(page,pageCount);
  const pageSlice=<T,>(items:T[])=>items.slice((currentPage-1)*pageSize,currentPage*pageSize);
  const edit=(order:Order,review?:Review)=>{setEditing({order,review});setScore(5);setContent("");setAnonymous(false);setValidation("");};
  return <section className="review-workspace"><div className="v3-account-toolbar" data-list-sticky><AdaptiveTabs label="评价分类" value={tab} items={[{value:"pending",label:"待评价",count:eligible.length},{value:"sent",label:"已评价",count:sent.length},{value:"received",label:"我收到的",count:received.length}]} onChange={setTab}/><span className="review-toolbar-hint">真实反馈，让每一次合作更好</span></div><ErrorNotice error={!editing?error:null}/>
    {tab==="pending"?eligible.length?pageSlice(eligible).map(o=><article className="account-review-card" key={o.id}><header><time>{o.createdAt}</time><span>订单号：{o.id}</span><b>{o.provider}</b><span className="v3-status v3-status-completed">已完成</span></header><div className="review-service"><ContentImage src={o.image} alt={o.name} placeholder="" placeholderIcon={<ImageSquare size={28}/>}/><div><Link to={`/services/${o.serviceId}`}><h2>{o.name}</h2></Link><p>{o.category} · {o.spec}</p></div><button className="button primary" onClick={()=>edit(o)}>去评价</button></div><footer><p><CheckCircle size={18}/>服务已完成，分享您的交付体验与合作感受。</p><Link className="v3-order-text-action" to={`/account/orders/services?order=${o.id}`}>查看订单详情</Link></footer></article>):<EmptyState title="暂无待评价订单" description="已完成的服务订单会展示在这里。您也可以查看已发表的评价。" action="查看已评价" onAction={()=>setTab("sent")}/>:current.length?pageSlice(current).map(r=>{const o=orders.find(o=>o.id===r.orderId);if(!o)return null;return <article className="account-review-card" key={r.id}><header><time>{o.createdAt}</time><span>订单号：{o.id}</span><b>{o.provider}</b>{r.hidden&&<span className="v3-status v3-status-closed">评价已隐藏</span>}</header><div className="review-service">{tab==="sent"&&<ContentImage src={o.image} alt={o.name} placeholder="" placeholderIcon={<ImageSquare size={28}/>}/>}<div><Link to={`/services/${o.serviceId}`}><h2>{o.name}</h2></Link><p>{o.category} · {o.spec}</p></div><Link className="v3-order-text-action" to={`/account/orders/services?order=${o.id}`}>订单详情</Link></div><div className="review-content"><div className="review-rating"><Stars score={r.score}/>{r.direction==="sent"&&<label className="review-anonymous"><input type="checkbox" role="switch" checked={r.anonymous} disabled={pending} onChange={e=>void onAction({type:"reviewAnonymous",reviewId:r.id,anonymous:e.target.checked})}/>匿名评价</label>}</div><p>{r.content||`已给出${r.score}星评价，未填写文字内容。`}</p><div className="review-bottom"><time>评价时间：{r.createdAt}</time>{r.direction==="sent"&&<div>{!r.followup&&<button className="v3-order-text-action" onClick={()=>edit(o,r)}>追加评价</button>}<button className="v3-order-text-action is-muted" disabled={pending} onClick={()=>void onAction({type:"reviewVisibility",reviewId:r.id,target:"review",hidden:!r.hidden})}>{r.hidden?"恢复展示":"隐藏评价"}</button></div>}</div>{r.followup&&<div className="review-followup"><strong><ChatCircleText size={17}/>追加评价{r.followup.hidden&&<span>已隐藏</span>}</strong><p>{r.followup.content}</p><div className="review-bottom"><time>{r.followup.createdAt}</time><button className="v3-order-text-action is-muted" disabled={pending} onClick={()=>void onAction({type:"reviewVisibility",reviewId:r.id,target:"followup",hidden:!r.followup!.hidden})}>{r.followup.hidden?"恢复追评":"隐藏追评"}</button></div></div>}{r.reply&&<blockquote><b>服务商回复</b>{r.reply}</blockquote>}</div></article>;}):<EmptyState title={tab==="sent"?"暂无已发表评价":"暂无收到的评价"} description="合作中的反馈会在这里集中展示。"/>}
    {listLength>0&&<div className="v3-account-pagination"><span>共 {listLength} 条记录</span><button className="button secondary" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>上一页</button><span>{currentPage} / {pageCount}</span><button className="button secondary" disabled={currentPage===pageCount} onClick={()=>setPage(currentPage+1)}>下一页</button></div>}
    <Modal open={!!editing} onOpenChange={open=>{if(!open&&!pending)setEditing(null);}} title={editing?.review?"追加评价":"评价本次服务"} description={editing?.order.name}>
      <form className="review-form" onSubmit={async e=>{e.preventDefault();if(!editing)return;if(editing.review&&!content.trim()){setValidation("请填写追评内容");return;}const ok=await onAction(editing.review?{type:"reviewFollowup",reviewId:editing.review.id,content:content.trim()}:{type:"review",orderId:editing.order.id,score,content:content.trim(),anonymous});if(ok){setEditing(null);setTab("sent");}}}>
        {!editing?.review&&<><label>服务评分</label><div className="review-score-input" role="group" aria-label="选择服务评分">{[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={`${n}星`} aria-pressed={score===n} onClick={()=>setScore(n)}><Star size={32} weight={n<=score?"fill":"regular"}/></button>)}<span>{score} 星</span></div></>}
        <label htmlFor="review-content">{editing?.review?"追评内容":"评价内容（选填）"}</label><textarea id="review-content" value={content} onChange={e=>setContent(e.target.value)} rows={5} maxLength={1000} placeholder="说说服务质量、沟通体验和交付情况，帮助其他企业了解这项服务。"/><small>{content.length} / 1000</small>{!editing?.review&&<label className="review-anonymous"><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/>匿名发表，不展示您的姓名</label>}<ErrorNotice error={validation||error}/><div className="v3-dialog-actions"><button type="button" className="button secondary" disabled={pending} onClick={()=>setEditing(null)}>取消</button><button className="button primary" disabled={pending}>{pending?"正在提交…":editing?.review?"发表追评":"提交评价"}</button></div>
      </form>
    </Modal>
  </section>;
}
